name: asteroidracers
description: A sample web application
dependencies:
  browser: '0.10.0+2'
  game_loop: '0.9.4'
  mime_type: '0.1.7'
  path: '1.3.6'
  stagexl: '0.11.0+1'
  stagexl_particle: '0.3.5+1'
  unittest: '0.11.0'
  protobuf: "0.4.0"
  vector_math: '1.4.3'
  neural_network: "0.0.4"
transformers:
- $dart2js:
    commandLineOptions: [--enable-enum]
