name: AsteroidRacers
description: A sample web application
dependencies:
  browser: '>=0.10.0+2'
  vector_math: '>=1.4.3'
  stagexl: '>=0.9.2+1'
  path: '>=1.1.0'
  unittest: ">=0.11.0"
  game_loop: ">=0.9.4"